# Dockerfile for FastAPI application
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the FastAPI application
COPY src/xfd_django .

# Set environment variable
ENV DJANGO_SETTINGS_MODULE=xfd_django.settings

# Command to run the FastAPI application
CMD ["uvicorn", "--workers", "4", "xfd_django.asgi:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
