# Dockerfile for FastAPI application
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
RUN pip install --upgrade pip setuptools wheel
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install the worker requirements for local development
COPY worker/requirements.txt worker/requirements.txt
RUN pip install --no-cache-dir -r worker/requirements.txt

# Copy the FastAPI application
COPY src/xfd_django .

# Copy the .pylintrc file
COPY .pylintrc .

# Set environment variable
ENV DJANGO_SETTINGS_MODULE=xfd_django.settings

# Command to run the FastAPI application
CMD ["uvicorn", "--workers", "4", "xfd_django.asgi:app", "--host", "0.0.0.0", "--port", "3000", "--reload"]
