---
service: crossfeed

frameworkVersion: '3'
useDotenv: true
configValidationMode: error

custom:
  adotLayerArn:
    us-east-1: arn:aws:lambda:us-east-1:615299751070:layer:AWSOpenTelemetryDistroPython:16
    us-east-2: arn:aws:lambda:us-east-2:615299751070:layer:AWSOpenTelemetryDistroPython:13
    us-west-1: arn:aws:lambda:us-west-1:615299751070:layer:AWSOpenTelemetryDistroPython:20
    us-west-2: arn:aws:lambda:us-west-2:615299751070:layer:AWSOpenTelemetryDistroPython:20
    us-gov-east-1: ${ssm:/crossfeed/${self:provider.stage}/adot_python_layer_arn, ''}
    us-gov-west-1: ${ssm:/crossfeed/${self:provider.stage}/adot_python_layer_arn, ''}
  adotLayerArnSelected: ${self:custom.adotLayerArn[${self:provider.region}]}
  customDomain:
    domainName: ${file(env.yml):${self:provider.stage}.DOMAIN, ''}
    basePath: ''
    certificateName: ${file(env.yml):${self:provider.stage}.CERT_DOMAIN, ''}
    stage: ${self:provider.stage}
    createRoute53Record: false
  prune:
    automatic: true
    includeLayers: true
    number: 3
  pythonRequirements:
    dockerizePip: true
    noDeploy:
      - boto3
      - botocore
      - docker
      - pytest
      - pytest-django
      - pytest-env
      - pylint
      - mypy
      - mypy-extensions
      - python-dotenv
      - pika
      - isort
      - black
      - pipdeptree
      - MarkupSafe
      - uvloop

  # Resource policies for GovCloud (Private) vs Non-GovCloud (Regional)
  privateResourcePolicy:
    - Effect: Deny
      Principal: '*'
      Action: 'execute-api:Invoke'
      Resource: execute-api:/${self:provider.stage}/*/*
      Condition:
        StringNotEquals:
          'aws:sourceVpce': ${file(env.yml):${self:provider.stage}.VPC_ENDPOINT, ''}
    - Effect: Allow
      Principal: '*'
      Action: execute-api:Invoke
      Resource: execute-api:/${self:provider.stage}/*/*

  regionalResourcePolicy:
    - Effect: Allow
      Principal: '*'
      Action: execute-api:Invoke
      Resource: execute-api:/${self:provider.stage}/*/*
      Condition:
        IpAddress:
          aws:SourceIp:
            'Fn::Split':
              - ','
              - ${file(env.yml):${self:provider.stage}.DMZ_CIDR, ''}

  # Conditional logic for GovCloud vs
  # non-GovCloud (Private endpoints require a VPC Endpoint)
  serverlessIfElse:
    - If: '"${file(env.yml):${self:provider.stage}.ENDPOINT_TYPE}" == "PRIVATE"'
      Set:
        provider.vpcEndpointIds:
          - ${file(env.yml):${self:provider.stage}.VPC_ENDPOINT, ''}
        provider.apiGateway.resourcePolicy: ${self:custom.privateResourcePolicy}
      ElseSet:
        provider.apiGateway.resourcePolicy: ${self:custom.regionalResourcePolicy}
      ElseExclude:
        - provider.vpcEndpointIds

provider:
  name: aws
  region: ${file(env.yml):${self:provider.stage}.REGION, ''}
  endpointType: ${file(env.yml):${self:provider.stage}.ENDPOINT_TYPE, ''}
  runtime: python3.11
  timeout: 30
  stage: ${opt:stage, 'dev'}
  environment: ${file(env.yml):${self:provider.stage}, ''}
  vpc: ${file(env.yml):${self:provider.stage}-vpc, ''}
  logs:
    restApi: true
  deploymentBucket:
    serverSideEncryption: AES256
  apiGateway:
    binaryMediaTypes:
      - image/*
      - font/*
    resourcePolicy:
      - Effect: Allow
        Principal: '*'
        Action: execute-api:Invoke
        Resource: execute-api:/${self:provider.stage}/*/*
  tracing:
    lambda: true


resources:
  Conditions:
    IsDMZ:
      Fn::Or:
        - Fn::Equals:
            - ${self:provider.stage}
            - staging-cd
        - Fn::Equals:
            - ${self:provider.stage}
            - integration
  Resources:
    ASMSyncQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stage}-asmSync-queue
        VisibilityTimeout: 18000  # 5 hours
        MaximumMessageSize: 262144  # 256 KB
        MessageRetentionPeriod: 604800  # 7 days

functions:
  - ${file(./src/tasks/functions.yml)}
  - ${file(./src/api/functions.yml)}

plugins:
  - serverless-iam-roles-per-function
  - serverless-better-credentials
  - serverless-domain-manager
  - serverless-dotenv-plugin
  - serverless-python-requirements
  - serverless-plugin-ifelse
  - serverless-prune-versions
