import { Cpe } from './cpe';
export interface Cve {
  id: string;
  name: string | null;
  description: string | null;
  modified_at: Date;
  published_at: Date;
  status: string | null;
  cvss_v2_source: string | null;
  cvss_v2_type: string | null;
  cvss_v2_version: string | null;
  cvss_v2_vector_string: string | null;
  cvss_v2_base_score: string | null;
  cvss_v2_base_severity: string | null;
  cvss_v2_exploitability_score: string | null;
  cvss_v2_impact_score: string | null;
  cvss_v3_source: string | null;
  cvss_v3_type: string | null;
  cvss_v3_version: string | null;
  cvss_v3_vector_string: string | null;
  cvss_v3_base_score: string | null;
  cvss_v3_base_severity: string | null;
  cvss_v3_exploitability_score: string | null;
  cvss_v3_impact_score: string | null;
  cvss_v4_source: string | null;
  cvss_v4_type: string | null;
  cvss_v4_version: string | null;
  cvss_v4_vector_string: string | null;
  cvss_v4_base_score: string | null;
  cvss_v4_base_severity: string | null;
  cvss_v4_exploitability_score: string | null;
  cvss_v4_impact_score: string | null;
  references: string[] | null;
  weaknesses: string[] | null;
  cpes: Cpe[];
}
