export const ENDPOINTS = {
  DOMAIN: '/domain/{domain_id}',
  DOMAIN_EXPORT: '/domain/export',
  DOMAIN_SEARCH: '/domain/search',
  GET_OAUTH_METADATA: '/auth/get-oauth-meta',
  LOGS_FILTERED_SEARCH: '/logs/filtered-search',
  LOGS_SEARCH: '/logs/search',
  METRICS_CUSTOMERS: '/metrics/customers',
  METRICS_SCAN: '/metrics/scans/{scan_id}',
  METRICS_SCANS: '/metrics/scans',
  NOTIFICATION: '/notifications/{notification_id}',
  NOTIFICATION_UPDATE: '/update_notification/{notification_id}',
  NOTIFICATIONS: '/notifications',
  OBJECT_STORE_PRESIGNED_URL: '/v1/object-store/presigned-url',
  OKTA_CALLBACK: '/auth/okta-callback',
  ORGANIZATION: '/organizations/{organization_id}',
  ORGANIZATION_ADD_USER: '/v2/organizations/{organization_id}/users',
  ORGANIZATION_APPROVE_ROLE:
    '/organizations/{organization_id}/roles/{role_id}/approve',
  ORGANIZATION_GRANULAR_SCAN_UPDATE:
    '/organizations/{organization_id}/granularScans/{scan_id}/update',
  ORGANIZATION_REMOVE_ROLE:
    '/organizations/{organization_id}/roles/{role_id}/remove',
  ORGANIZATION_UPDATE: '/update_organization/{organization_id}',
  ORGANIZATION_UPSERT: '/organizations_upsert',
  ORGANIZATIONS: '/organizations',
  ORGANIZATIONS_REGION: '/organizations/region_id/{region_id}',
  ORGANIZATIONS_SEARCH: '/v2/organizations/search',
  ORGANIZATIONS_SEARCH_ES: '/search/organizations',
  ORGANIZATIONS_STATE: '/organizations/state/{state}',
  ORGANIZATIONS_TAGS: '/organizations/tags',
  QUEUES_SEARCH: '/queues/search',
  REGIONS: '/regions',
  SAVED_SEARCH: '/saved-searches/{saved_search_id}',
  SAVED_SEARCH_UPDATE: '/update_saved-searches/{saved_search_id}',
  SAVED_SEARCHES: '/saved-searches',
  SCAN: '/scans/{scan_id}',
  SCAN_RUN: '/scans/{scan_id}/run',
  SCAN_SCHEDULER: '/scheduler/invoke',
  SCAN_TASKS_KILL: '/scan-tasks/{scan_task_id}/kill',
  SCAN_TASK_LOGS: '/scan-tasks/{scan_task_id}/logs',
  SCAN_UPDATE: '/update_scan/{scan_id}',
  SCANS: '/scans',
  SCANS_GRANULAR: '/granularScans',
  SCANS_TASK_SEARCH: '/scan-tasks/search',
  SEARCH_ES: '/search',
  SEARCH_ES_EXPORT: '/search/export',
  SEARCH_ORGANIZATIONS: '/search/organizations',
  STATS: '/stats',
  STATS_COMPARE: '/stats/compare',
  STATS_TRENDS: '/stats/trends',
  STATS_TRENDS_CONDENSED: '/stats/condensed_trends',
  STATS_TRENDS_V2: '/v2/stats/trends',
  USER: '/users/{user_id}',
  USER_ACCEPT_TERMS: '/users/me/acceptTerms',
  USER_UPDATE_V2: '/v2/update_user/{user_id}',
  USERS: '/users',
  USERS_ME: '/users/me',
  USERS_REGISTER_APPROVE: '/users/{user_id}/register/approve',
  USERS_REGISTER_DENY: '/users/{user_id}/register/deny',
  USERS_REGION_ID: '/users/region_id/{region_id}',
  USERS_SEARCH_V2: '/v2/users/search',
  USERS_STATE: '/users/state/{state}',
  USERS_V2: '/v2/users',
  V1_CALLBACK: '/auth/callback',
  VULNERABILITIES_EXPORT: '/vulnerabilities/export',
  VULNERABILITIES_SEARCH: '/vulnerabilities/search',
  VULNERABILITY: '/vulnerabilities/{vulnerability_id}',
  VULNERABILITY_DETAILS_V2: '/v2/vulnerability_details/{vulnerability_id}',
  VULNERABILITY_V2: '/v2/vulnerabilities/{vulnerability_id}'
};
