"""Helpers for reading generated P&E report PDFs from a local directory.

Local-only alternative to pe_mailer.s3_reports, for testing pe-mailer against
reports generated by `make -C backend/pe run-reports` without needing an S3
bucket populated first. Layout matches pe_reports.report_generator's local
OUTPUT_DIRECTORY convention 1:1 -- one subfolder per org -- so an OUTPUT_DIR
from a local run-reports invocation can be pointed at directly, e.g.:

    <LOCAL_REPORTS_DIR>/DHS/Posture_and_Exposure_Report-DHS-2026-07-15.pdf
    <LOCAL_REPORTS_DIR>/DHS/Posture-and-Exposure-ASM-Summary_DHS_2026-07-15.pdf

Enabled by setting MAILER_LOCAL_REPORTS_DIR (wired up by
peMailerController.start_local_docker_mailer_task's PE_LOCAL_REPORTS_DIR
bind mount for local Docker runs) -- when unset, pe-mailer reads from S3 as
normal (see pe_mailer.s3_reports). Nothing in this module talks to AWS.
"""
# Standard Python Libraries
import os


def report_path(local_dir: str, report_date: str, cyhy_db_name: str) -> str:
    """Return the local path of an org's plaintext report PDF.

    Matches the filename report_generator.py writes at
    ``{output_directory}/{org_code}/Posture_and_Exposure_Report-{org_code}-{datestring}.pdf``.
    """
    return os.path.join(
        local_dir,
        cyhy_db_name,
        f"Posture_and_Exposure_Report-{cyhy_db_name}-{report_date}.pdf",
    )


def asm_summary_path(local_dir: str, report_date: str, cyhy_db_name: str) -> str:
    """Return the local path of an org's plaintext ASM summary PDF.

    Matches the filename report_generator.py writes at
    ``Posture-and-Exposure-ASM-Summary_{org_code}_{end_date}.pdf`` (note the
    underscore separators, unlike the report filename above -- see
    pe_mailer.s3_reports.asm_summary_object_key, which documents the same
    quirk for the S3 convention this mirrors).
    """
    return os.path.join(
        local_dir,
        cyhy_db_name,
        f"Posture-and-Exposure-ASM-Summary_{cyhy_db_name}_{report_date}.pdf",
    )
