"""Region state mapping dictionary."""

REGION_STATE_MAP = {
    "Alabama": "4",
    "Alaska": "10",
    "American Samoa": "9",
    "Arkansas": "6",
    "Arizona": "9",
    "California": "9",
    "Colorado": "8",
    "Commonwealth Northern Mariana Islands": "9",
    "Connecticut": "1",
    "Delaware": "3",
    "District of Columbia": "3",
    "Federal States of Micronesia": "9",
    "Florida": "4",
    "Georgia": "4",
    "Guam": "9",
    "Hawaii": "9",
    "Idaho": "10",
    "Illinois": "5",
    "Indiana": "5",
    "Iowa": "7",
    "Kansas": "7",
    "Kentucky": "4",
    "Louisiana": "6",
    "Maine": "1",
    "Maryland": "3",
    "Massachusetts": "1",
    "Michigan": "5",
    "Minnesota": "5",
    "Mississippi": "4",
    "Missouri": "7",
    "Montana": "8",
    "Nebraska": "7",
    "Nevada": "9",
    "New Hampshire": "1",
    "New Jersey": "2",
    "New Mexico": "6",
    "New York": "2",
    "North Carolina": "4",
    "North Dakota": "8",
    "Ohio": "5",
    "Oklahoma": "6",
    "Oregon": "10",
    "Pennsylvania": "3",
    "Puerto Rico": "2",
    "Republic of Marshall Islands": "9",
    "Rhode Island": "1",
    "South Carolina": "4",
    "South Dakota": "8",
    "Tennessee": "4",
    "Texas": "6",
    "Utah": "8",
    "Vermont": "1",
    "Virgin Islands": "2",
    "Virginia": "3",
    "Washington": "10",
    "West Virginia": "3",
    "Wisconsin": "5",
    "Wyoming": "8",
}

STATE_ABBR_MAP = {
    "Alabama": "AL",
    "Alaska": "AK",
    "American Samoa": "AS",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "District of Columbia": "DC",
    "Florida": "FL",
    "Georgia": "GA",
    "Guam": "GU",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Puerto Rico": "PR",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virgin Islands": "VI",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "Commonwealth Northern Mariana Islands": "MP",
    "Federal States of Micronesia": "FM",
    "Republic of Marshall Islands": "MH",
}
