export const testOrganization = {
  id: 'd7d6e913-0370-4f43-aebc-6bd727adc70e',
  name: 'test org',
  root_domains: ['example.com'],
  ip_blocks: [],
  user_roles: [],
  scan_tasks: [],
  is_passive: false,
  granular_scans: [],
  tags: [],
  parent: null,
  children: [],
  pending_domains: [],
  country: 'US',
  state: 'LA',
  state_fips: 22,
  state_name: 'Louisiana',
  county: 'Calcasieu Parish',
  county_fips: 22019,
  acronym: 'TEST',
  type: 'Federal'
};
