-- Populates the database with RSC questions and their associated categories and resources
with  data("questionName", "longForm", "questionNumber", "questionDescription", "categoryName", "categoryNumber", "shortName", "resourceDescription", "resourceName", type, url) as (
    values
        ('u_it_org_size', 'Select the option that best matches your organization based on number of Information Technology (IT) personnel supporting you. Include partially and fully dedicate staff and IT personnel contracted through a Managed Service Provider (MSP).', 'A1.01', null, 'Landing Page', 'A1', 'Landing Page', null, null, null, null),
        ('u_pw_different', 'Are your work passwords different from your personal passwords?', 'A2.01', null, 'Security Best Practices', 'A2', 'Best Practices', 'To prevent a security incident in one of your accounts from affecting all of your accounts, it''s important to use unique passwords. Check out this article to learn more.', 'Choosing and Protecting Passwords', 'article', 'https://www.cisa.gov/news-events/news/choosing-and-protecting-passwords'),
        ('u_pw_strong', 'Are your work passwords strong passwords? ', 'A2.02', 'Strong passwords are longer than 8 characters, a combination of numbers, letters, and characters, with at least one capital and lower case letter', 'Security Best Practices', 'A2', 'Best Practices', 'A great first step to securing user accounts is to learn how to choose strong passwords. Watch this short video from CISA to learn more.', 'Secure Our World - Keep Your Accounts Safe with Strong Passwords', 'video', 'https://www.youtube.com/watch?v=FZoB7yUGh7Y'),
        ('u_mfa_enabled', 'Do you have multi-factor authentication enabled on your work computers and systems? ', 'A2.03', 'Multi-Factor Authentication (MFA) is a layered approach to securing data and applications where a system requires a user to present a combination of two or more credentials to verify a user’s identity for login.', 'Security Best Practices', 'A2', 'Best Practices', 'As this short video will explain, a password is not enough. CISA strongly recommends that individuals and organizations implement multi-factor authentication to keep your accounts and data safe.', 'Secure Our World - Make Your Accounts Safe with Multifactor Authentication (MFA)', 'video', 'https://www.youtube.com/watch?v=XIlF2qkav5c'),
        ('u_backup_data', 'Do you regularly back up your important work data? ', 'A2.04', null, 'Security Best Practices', 'A2', 'Best Practices', 'To ensure the availabilty of your data, it''s important to make regular backups.  This guidline from CISA outlines some options for how to backup your data.', 'Data Backup Options', 'publication', 'https://www.cisa.gov/sites/default/files/publications/data_backup_options.pdf'),
        ('u_backup_method', 'What methods do you use to backup your data?', 'A2.05', null, 'Security Best Practices', 'A2', 'Best Practices', null, null, null, null),
        ('u_backup_auto', 'Do you enable automatic backups?', 'A2.06', null, 'Security Best Practices', 'A2', 'Best Practices', 'Establish regular automated backups and redundancies of key systems. Employ a backup solution that automatically and continuously backs up your business-critical data and system configurations. Regular backups protect against ransomware and malware attacks. Use on-site and remote backup methods to protect vulnerable information. ', 'Cyber Essentials Toolkit: Your Data', 'publication', 'https://www.cisa.gov/sites/default/files/publications/Cyber%20Essentials%20Toolkit%205%2020201015_508.pdf'),
        ('u_backup_auto', 'Do you enable automatic backups?', 'A2.06', null, 'Security Best Practices', 'A2', 'Best Practices', 'CISA''s Cyber Essentials Toolkit provides guidance on where to start when implementing cybersecurity best practices. Check out Chapter 2 to learn about cybersecurity and your people', 'Cyber Essentials Toolkit: Your Staff, Your Users', 'publication', 'https://www.cisa.gov/sites/default/files/publications/Cyber%2520Essentials%2520Toolkit%25202%252020200701.pdf'),
        ('u_backup_access', 'Can you quickly access your data backups?', 'A2.07', null, 'Security Best Practices', 'A2', 'Best Practices', 'Establish regular automated backups and redundancies of key systems. Employ a backup solution that automatically and continuously backs up your business-critical data and system configurations. Regular backups protect against ransomware and malware attacks. Use on-site and remote backup methods to protect vulnerable information. ', 'Cyber Essentials Toolkit: Your Data', 'publication', 'https://www.cisa.gov/sites/default/files/publications/Cyber%20Essentials%20Toolkit%205%2020201015_508.pdf'),
        ('u_backup_access', 'Can you quickly access your data backups?', 'A2.07', null, 'Security Best Practices', 'A2', 'Best Practices', 'CISA''s Cyber Essentials Toolkit provides guidance on where to start when implementing cybersecurity best practices. Check out Chapter 3 to learn about securing your systems.', 'Cyber Essentials Toolkit: Your System', 'publication', 'https://www.cisa.gov/sites/default/files/publications/Cyber%2520Essentials%2520Toolkit%25203%252020200806_508.pdf'),
        ('u_device_type', 'What type of information technology (IT) devices do you use for work?', 'A2.08', null, 'Security Best Practices', 'A2', 'Best Practices', 'Keep your organization safe by ensuring you have policies and procedures to prevent unauthorized devices from connecting to your network. This article outlines the risks posed by portable devices.', 'The Risks of Portable Devices', 'publication', 'https://www.cisa.gov/sites/default/files/publications/RisksOfPortableDevices.pdf'),
        ('u_device_type', 'What type of information technology (IT) devices do you use for work?', 'A2.08', null, 'Security Best Practices', 'A2', 'Best Practices', 'Establish regular automated backups and redundancies of key systems. Employ a backup solution that automatically and continuously backs up your business-critical data and system configurations. Regular backups protect against ransomware and malware attacks. Use on-site and remote backup methods to protect vulnerable information. ', 'Cyber Essentials Toolkit: Your Data', 'publication', 'https://www.cisa.gov/sites/default/files/publications/Cyber%20Essentials%20Toolkit%205%2020201015_508.pdf'),
        ('u_security_features', 'Do you have any of the following security features enabled?\n\nScreen to auto-lock after a period of inactivity\nPIN code, passcode, fingerprint, face ID (or other biometric) to access your device\nFind my device (for Apple devices)\nPlay protect (for Android devices)', 'A2.09', null, 'Security Best Practices', 'A2', 'Best Practices', 'To keep your information secure, it''s important to ensure your devices have security features enabled. You should set your screen to auto-lock after a period of inactivity, and unlocking the device should require a PIN, Password, or Biometrics (such as a face ID or fingerprint). ', 'Are your mobile settings leaving you vulnerable?', 'video', 'https://www.youtube.com/watch?v=dvqBrfaTB0A'),
        ('u_security_features', 'Do you have any of the following security features enabled?\n\nScreen to auto-lock after a period of inactivity\nPIN code, passcode, fingerprint, face ID (or other biometric) to access your device\nFind my device (for Apple devices)\nPlay protect (for Android devices)', 'A2.09', null, 'Security Best Practices', 'A2', 'Best Practices', 'This Guide helps professionals develop a training plan based on their current skill level and desired career opportunities.', 'Cybersecurity Workforce Training Guide', 'guide', 'https://www.cisa.gov/sites/default/files/publications/Cybersecurity%2520Workforce%2520Training%2520Guide%25207.28.21%2520508c.pdf'),
        ('u_fw_av', 'Do you use a combination of firewall and antivirus on your work computers?', 'A2.10', 'Firewall and antivirus are security features that are built into Windows and macOS, and can be found in your computer''s settings. You can also choose to buy these products from a third party.', 'Security Best Practices', 'A2', 'Best Practices', 'Read this article to learn more about how Anti-virus software can identify and block many viruses before they can infect your computer.', 'Understanding Anti-virus software', 'article', 'https://www.cisa.gov/news-events/news/understanding-anti-virus-software'),
        ('u_fw_av', 'Do you use a combination of firewall and antivirus on your work computers?', 'A2.10', 'Firewall and antivirus are security features that are built into Windows and macOS, and can be found in your computer''s settings. You can also choose to buy these products from a third party.', 'Security Best Practices', 'A2', 'Best Practices', 'As organizations move more and more of their IT infrastructure to the cloud, it''s important to ensure that your organization has vulnerability management in place in your virtual environment. Check out this vide from the 4th Annual National Cybersecurity Summit to learn more.', 'Cloud Vulnerability Management', 'video', 'https://www.youtube.com/watch?v=qgZ--uzIm_w'),
        ('u_disable_svcs', 'Do you disable services not required for business purposes?', 'A2.11', null, 'Security Best Practices', 'A2', 'Best Practices', 'Disabling services that you aren''t using is one step you can take to keep your data safe. This article about home network security explains why and provides some other simple recommendations.', 'Network Security', 'article', 'https://www.cisa.gov/news-events/news/home-network-security'),
        ('u_disable_svcs', 'Do you disable services not required for business purposes?', 'A2.11', null, 'Security Best Practices', 'A2', 'Best Practices', 'CISA''s Cyber Essentials Toolkit provides guidance on where to start when implementing cybersecurity best practices. Check out this chapter to learn more about SCRM.', 'Cyber Essentials: Supply Chain Risk Management (SCRM)', 'guide', 'https://www.cisa.gov/sites/default/files/publications/ict_scrm_essentials_508.pdf'),
        ('u_software_updates', 'Do you stay current on software updates?', 'A2.12', null, 'Security Best Practices', 'A2', 'Best Practices', 'This guide provides recommendations on how to plan for and respond to cyber incidents.', 'Planning Considerations for Cyber Incidents: Guidance for Emergency Managers', 'resource', 'https://www.cisa.gov/resources-tools/resources/planning-considerations-cyber-incidents-guidance-emergency-managers'),
        ('u_software_updates', 'Do you stay current on software updates?', 'A2.12', null, 'Security Best Practices', 'A2', 'Best Practices', 'Many software updates are created to fix security risks, so it''s important to keep your software up to date. Watch this short video to learn more.', 'Secure Our World - Stay Safe by Updating Your Software', 'video', 'https://www.youtube.com/watch?v=o1WsviOK9fE'),
        ('u_reputable_software', 'Do you install apps and software from official and/or reputable sources?', 'A2.13', null, 'Security Best Practices', 'A2', 'Best Practices', 'This might mean only downloading from an official app store such as Apple App Store or Google Play, or researching the brand or checking its reviews first. For more details, read the Securing the Software Supply Chain Fact Sheet.', 'Securing the Software Supply Chain', 'publication', 'https://www.cisa.gov/sites/default/files/2023-01/esf_securing_the_software_supply_chain_customer_slicksheet.pdf'),
        ('u_iam_security', 'Does your organization have security controls in place that appropriately identify, authenticate, and authorize users?', 'B1.01', null, 'Baseline', 'B1', 'Baseline', 'CISA''s Cyber Essentials Toolkit provides guidance on where to start when implementing cybersecurity best practices. Check out Chapter 2 to learn about cybersecurity and your people', 'Cyber Essentials Toolkit: Your Staff, Your Users', 'publication', 'https://www.cisa.gov/sites/default/files/publications/Cyber%2520Essentials%2520Toolkit%25202%252020200701.pdf'),
        ('u_iam_security', 'Does your organization have security controls in place that appropriately identify, authenticate, and authorize users?', 'B1.01', null, 'Baseline', 'B1', 'Baseline', 'A great first step to securing user accounts is to learn how to choose strong passwords. Watch this short video from CISA to learn more.', 'Secure Our World - Keep Your Accounts Safe with Strong Passwords', 'video', 'https://www.youtube.com/watch?v=FZoB7yUGh7Y'),
        ('u_device_config', 'Do you have device configuration policies and controls in place to manage the security, provisioning, and deployment of devices across the organization?', 'B1.02', 'Configuration: The possible conditions, parameters, and specifications with which an information system or system component can be described or arranged.', 'Baseline', 'B1', 'Baseline', 'Check out this post on CISA''s blog to get started securing network devices.', 'Securing Network Infrastructure Devices', 'blog', 'https://www.cisa.gov/news-events/news/securing-network-infrastructure-devices'),
        ('u_device_config', 'Do you have device configuration policies and controls in place to manage the security, provisioning, and deployment of devices across the organization?', 'B1.02', 'Configuration: The possible conditions, parameters, and specifications with which an information system or system component can be described or arranged.', 'Baseline', 'B1', 'Baseline', 'CISA''s Cyber Essentials Toolkit provides guidance on where to start when implementing cybersecurity best practices. Check out Chapter 3 to learn about securing your systems.', 'Cyber Essentials Toolkit: Your System', 'publication', 'https://www.cisa.gov/sites/default/files/publications/Cyber%2520Essentials%2520Toolkit%25203%252020200806_508.pdf'),
        ('u_cia_data', 'Do you have security controls and monitoring in place to protect the Confidentiality, Integrity, and Availability (CIA) of data?', 'B1.03', 'The CIA triad is a widely used information security model that can guide an organization’s efforts and policies aimed at keeping its data secure. The initials stand for the three principles on which information security rests: - Confidentiality: Only authorized users and processes should be able to access or modify data - Integrity: Data should be maintained in a correct state and nobody should be able to improperly modify it, either accidentally or maliciously - Availability: Authorized users should be able to access data whenever they need to do so', 'Baseline', 'B1', 'Baseline', 'If you''re ready to start securing your network, check out this article with some cybersecurity basics.', 'What is Cybersecurity?', 'article', 'https://www.cisa.gov/news-events/news/what-cybersecurity'),
        ('u_cia_data', 'Do you have security controls and monitoring in place to protect the Confidentiality, Integrity, and Availability (CIA) of data?', 'B1.03', 'The CIA triad is a widely used information security model that can guide an organization’s efforts and policies aimed at keeping its data secure. The initials stand for the three principles on which information security rests: - Confidentiality: Only authorized users and processes should be able to access or modify data - Integrity: Data should be maintained in a correct state and nobody should be able to improperly modify it, either accidentally or maliciously - Availability: Authorized users should be able to access data whenever they need to do so', 'Baseline', 'B1', 'Baseline', 'Establish regular automated backups and redundancies of key systems. Employ a backup solution that automatically and continuously backs up your business-critical data and system configurations. Regular backups protect against ransomware and malware attacks. Use on-site and remote backup methods to protect vulnerable information. ', 'Cyber Essentials Toolkit: Your Data', 'publication', 'https://www.cisa.gov/sites/default/files/publications/Cyber%20Essentials%20Toolkit%205%2020201015_508.pdf'),
        ('u_governance_training', 'Does your organization develop and practice information security governance across the organization and provide cybersecurity training for all employees?', 'B1.04', 'Security governance: a process for overseeing the cybersecurity teams who are responsible for mitigating business risks. Security governance leaders make the decisions that allow risks to be prioritized so that security efforts are focused on business priorities rather than their own.', 'Baseline', 'B1', 'Baseline', 'This Guide helps professionals develop a training plan based on their current skill level and desired career opportunities.', 'Cybersecurity Workforce Training Guide', 'guide', 'https://www.cisa.gov/sites/default/files/publications/Cybersecurity%2520Workforce%2520Training%2520Guide%25207.28.21%2520508c.pdf'),
        ('u_governance_training', 'Does your organization develop and practice information security governance across the organization and provide cybersecurity training for all employees?', 'B1.04', 'Security governance: a process for overseeing the cybersecurity teams who are responsible for mitigating business risks. Security governance leaders make the decisions that allow risks to be prioritized so that security efforts are focused on business priorities rather than their own.', 'Baseline', 'B1', 'Baseline', 'For guidance on the importance of establishing security governance within your organization, take a look at the resources on the SAFECOM Governance page.', 'SAFECOM Governance Resources', 'resource', 'https://www.cisa.gov/safecom/governance'),
        ('u_vul_management', 'Does your organization have a process for Vulnerability Management?', 'B1.05', 'Vulnerability Management: the process of continuously identifying, evaluating, treating, and reporting the weaknesses in a system that could be exploited by a threat actor', 'Baseline', 'B1', 'Baseline', 'To get started with Vulnerability Management, download this comprehensive guide.', 'Vulnerability Management', 'guide', 'https://www.cisa.gov/sites/default/files/publications/CRR_Resource_Guide-VM_0.pdf'),
        ('u_vul_management', 'Does your organization have a process for Vulnerability Management?', 'B1.05', 'Vulnerability Management: the process of continuously identifying, evaluating, treating, and reporting the weaknesses in a system that could be exploited by a threat actor', 'Baseline', 'B1', 'Baseline', 'As organizations move more and more of their IT infrastructure to the cloud, it''s important to ensure that your organization has vulnerability management in place in your virtual environment. Check out this vide from the 4th Annual National Cybersecurity Summit to learn more.', 'Cloud Vulnerability Management', 'video', 'https://www.youtube.com/watch?v=qgZ--uzIm_w'),
        ('u_supply_chain_risk', 'Do you have a Supply Chain Risk Management process, or is risk management a consideration in your Supply Chain Management process?', 'B1.06', 'Supply Chain Risk Management (SCRM): A systematic process for managing cyber supply chain risk exposures, threats, and vulnerabilities throughout the supply chain and developing risk response strategies to the risks presented by the supplier, the supplied products and services, or the supply chain.', 'Baseline', 'B1', 'Baseline', 'Watch this webinar to learn about the importance of Supply Chain Risk Management and get started implementing SCRM in your organization.', 'SCRM Webinar', 'video', 'https://www.youtube.com/watch?v=3Um_XY-Ahis'),
        ('u_supply_chain_risk', 'Do you have a Supply Chain Risk Management process, or is risk management a consideration in your Supply Chain Management process?', 'B1.06', 'Supply Chain Risk Management (SCRM): A systematic process for managing cyber supply chain risk exposures, threats, and vulnerabilities throughout the supply chain and developing risk response strategies to the risks presented by the supplier, the supplied products and services, or the supply chain.', 'Baseline', 'B1', 'Baseline', 'CISA''s Cyber Essentials Toolkit provides guidance on where to start when implementing cybersecurity best practices. Check out this chapter to learn more about SCRM.', 'Cyber Essentials: Supply Chain Risk Management (SCRM)', 'guide', 'https://www.cisa.gov/sites/default/files/publications/ict_scrm_essentials_508.pdf'),
        ('u_inc_response_plan', 'Do you have an Incident Response and Recovery plan?', 'B1.07', 'Incident Response Plan: A set of predetermined and documented procedures to detect and respond to a cyber incident.', 'Baseline', 'B1', 'Baseline', 'When incidents happen, your organization will recover faster if you already have a plan in place. Download this article to get started.', 'Incident Response Plan Basics', 'publication', 'https://www.cisa.gov/sites/default/files/publications/Incident-Response-Plan-Basics_508c.pdf'),
        ('u_inc_response_plan', 'Do you have an Incident Response and Recovery plan?', 'B1.07', 'Incident Response Plan: A set of predetermined and documented procedures to detect and respond to a cyber incident.', 'Baseline', 'B1', 'Baseline', 'This guide provides recommendations on how to plan for and respond to cyber incidents.', 'Planning Considerations for Cyber Incidents: Guidance for Emergency Managers', 'resource', 'https://www.cisa.gov/resources-tools/resources/planning-considerations-cyber-incidents-guidance-emergency-managers'),
        ('u_pw_length', 'Do your systems require a minimum password length of 15 characters (including OT systems, where technically feasible)?', 'C1.01', 'Operational Technology (OT): Programmable systems or devices that interact with the physical environment (or manage devices
that interact with the physical environment). These systems/devices detect or cause a direct change through the monitoring and/or control of devices, processes, and events. Examples include ICSs, building management systems, fire control systems, andphysical access control mechanisms.', 'Identity and Access Management', 'C1', 'IAM', 'To prevent a security incident in one of your accounts from affecting all of your accounts, it''s important to use unique passwords. Check out this article to learn more.', 'Choosing and Protecting Passwords', 'article', 'https://www.cisa.gov/news-events/news/choosing-and-protecting-passwords'),
        ('u_pw_length', 'Do your systems require a minimum password length of 15 characters (including OT systems, where technically feasible)?', 'C1.01', 'Operational Technology (OT): Programmable systems or devices that interact with the physical environment (or manage devices
that interact with the physical environment). These systems/devices detect or cause a direct change through the monitoring and/or control of devices, processes, and events. Examples include ICSs, building management systems, fire control systems, andphysical access control mechanisms.', 'Identity and Access Management', 'C1', 'IAM', 'This offering is a password security auditing and password recovery tool available for many operating systems.', 'John the Ripper Password Cracker', 'tool', 'https://www.openwall.com/john/'),
        ('u_log_unsuccessful_login', 'Do you log all unsuccessful login attempts and provide security teams with alerts? If a certain number of unsuccessful logins occur over a short period of time?', 'C1.02', 'Logs: A record of the events occurring within an organization’s systems and networks.', 'Identity and Access Management', 'C1', 'IAM', 'Logging is an important part of any organization''s security posture. CISA has rolled out a new service that will make logging a breeze for your organization. Click the link to learn more!', 'Logging Made Easy (LME)', 'tool', 'https://www.cisa.gov/resources-tools/services/logging-made-easy'),
        ('u_log_unsuccessful_login', 'Do you log all unsuccessful login attempts and provide security teams with alerts? If a certain number of unsuccessful logins occur over a short period of time?', 'C1.02', 'Logs: A record of the events occurring within an organization’s systems and networks.', 'Identity and Access Management', 'C1', 'IAM', 'Security Onion is a free and open Linux distribution for threat hunting, enterprise security monitoring, and log management.', 'Security Onion', 'tool', 'https://securityonionsolutions.com/software'),
        ('u_change_default_pw', 'Do you change default passwords on all your IT and OT assets to the maximum extent possible, and implement compensating security controls wherever it is not?', 'C1.03', 'Default Passwords: Factory default software configurations for embedded systems, devices, and appliances often include simple,
publicly documented passwords. These systems usually do not provide a full operating system interface for user management,
and the default passwords are typically identical (shared) among all systems from a vendor or within product lines. Default
passwords are intended for initial testing, installation, and configuration operations, and many vendors recommend changing the
default password before deploying the system in a production environment.

Information Technology (IT): Any equipment or interconnected system or subsystem of equipment used in the automatic
acquisition, storage, analysis, evaluation, manipulation, management, movement, control, display, switching, interchange,
transmission, or reception of data or information.

Operational Technology (OT): Programmable systems or devices that interact with the physical environment (or manage devices
that interact with the physical environment). These systems/devices detect or cause a direct change through the monitoring and/or control of devices, processes, and events. Examples include ICSs, building management systems, fire control systems, andphysical access control mechanisms.', 'Identity and Access Management', 'C1', 'IAM', 'It''s important to change the default passwords on all of your assets. Check out this list of other common "Bad Practices" that might be making it easier for attackers to target your organization.', 'Bad Practices', 'article', 'https://www.cisa.gov/news-events/news/bad-practices-0'),
        ('u_change_default_pw', 'Do you change default passwords on all your IT and OT assets to the maximum extent possible, and implement compensating security controls wherever it is not?', 'C1.03', 'Default Passwords: Factory default software configurations for embedded systems, devices, and appliances often include simple,
publicly documented passwords. These systems usually do not provide a full operating system interface for user management,
and the default passwords are typically identical (shared) among all systems from a vendor or within product lines. Default
passwords are intended for initial testing, installation, and configuration operations, and many vendors recommend changing the
default password before deploying the system in a production environment.

Information Technology (IT): Any equipment or interconnected system or subsystem of equipment used in the automatic
acquisition, storage, analysis, evaluation, manipulation, management, movement, control, display, switching, interchange,
transmission, or reception of data or information.

Operational Technology (OT): Programmable systems or devices that interact with the physical environment (or manage devices
that interact with the physical environment). These systems/devices detect or cause a direct change through the monitoring and/or control of devices, processes, and events. Examples include ICSs, building management systems, fire control systems, andphysical access control mechanisms.', 'Identity and Access Management', 'C1', 'IAM', 'AllStar is a GitHub application for enforcing security policies and permissions.', 'Allstar', 'tool', 'https://github.com/ossf/allstar'),
        ('u_strong_mfa', 'Do you use MFA for access to all IT/OT assets, using the strongest available method possible?', 'C1.04', 'Multi-Factor Authentication (MFA): Multifactor authentication is a layered approach to securing data and applications where a system requires a user to present a combination of two or more credentials to verify a user’s identity for login.

Organizations should implement MFA for access to assets using the strongest available method for that asset). MFA options sorted by strength, high to low, are as follows:
1. Hardware-based, phishing-resistant MFA (e.g., FIDO/WebAuthn or public key infrastructure (PKI) based - see CISA guidance in”Resources”);
2. If such hardware-based MFA is not available, then mobile app-based soft tokens (preferably push notification with number matching) or emerging technology such as FIDO passkeys are used;
3. MFA via short message service (SMS) or voice only used when no other options are possible.

Phishing-Resistant MFA: As defined in OMB Memorandum 22-09, authentication processes designed to detect and prevent
disclosure of authentication secrets and outputs to a website or application masquerading as a legitimate system.

Information Technology (IT): Any equipment or interconnected system or subsystem of equipment used in the automatic
acquisition, storage, analysis, evaluation, manipulation, management, movement, control, display, switching, interchange,
transmission, or reception of data or information.

Operational Technology (OT): Programmable systems or devices that interact with the physical environment (or manage devices
that interact with the physical environment). These systems/devices detect or cause a direct change through the monitoring and/or control of devices, processes, and events. Examples include ICSs, building management systems, fire control systems, and physical access control mechanisms.', 'Identity and Access Management', 'C1', 'IAM', 'As this short video will explain, a password is not enough. CISA strongly recommends that individuals and organizations implement multi-factor authentication to keep your accounts and data safe.', 'Secure Our World - Make Your Accounts Safe with Multifactor Authentication (MFA)', 'video', 'https://www.youtube.com/watch?v=XIlF2qkav5c'),
        ('u_strong_mfa', 'Do you use MFA for access to all IT/OT assets, using the strongest available method possible?', 'C1.04', 'Multi-Factor Authentication (MFA): Multifactor authentication is a layered approach to securing data and applications where a system requires a user to present a combination of two or more credentials to verify a user’s identity for login.

Organizations should implement MFA for access to assets using the strongest available method for that asset). MFA options sorted by strength, high to low, are as follows:
1. Hardware-based, phishing-resistant MFA (e.g., FIDO/WebAuthn or public key infrastructure (PKI) based - see CISA guidance in”Resources”);
2. If such hardware-based MFA is not available, then mobile app-based soft tokens (preferably push notification with number matching) or emerging technology such as FIDO passkeys are used;
3. MFA via short message service (SMS) or voice only used when no other options are possible.

Phishing-Resistant MFA: As defined in OMB Memorandum 22-09, authentication processes designed to detect and prevent
disclosure of authentication secrets and outputs to a website or application masquerading as a legitimate system.

Information Technology (IT): Any equipment or interconnected system or subsystem of equipment used in the automatic
acquisition, storage, analysis, evaluation, manipulation, management, movement, control, display, switching, interchange,
transmission, or reception of data or information.

Operational Technology (OT): Programmable systems or devices that interact with the physical environment (or manage devices
that interact with the physical environment). These systems/devices detect or cause a direct change through the monitoring and/or control of devices, processes, and events. Examples include ICSs, building management systems, fire control systems, and physical access control mechanisms.', 'Identity and Access Management', 'C1', 'IAM', 'A password is not enough. CISA strongly recommends that individuals and organizations implement multi-factor authentication to keep your accounts and data safe. Check out CISA''s MFA Resource page to learn more.', 'CISA MFA Resources', 'resource', 'https://www.cisa.gov/MFA'),
        ('u_separate_admin', 'Do you ensure all user and administrator or super-user accounts are kept separate and privileges are re-evaluated on a recurring basis?', 'C1.05', null, 'Identity and Access Management', 'C1', 'IAM', 'Users should only have the minimum privileges necessary to do their work. This article explains the importance of separating accounts and the principle of "least privilege."', 'Defend Priveleges and Accounts', 'article', 'https://media.defense.gov/2019/Sep/09/2002180330/-1/-1/0/Defend%20Privileges%20and%20Accounts%20-%20Copy.pdf'),
        ('u_separate_admin', 'Do you ensure all user and administrator or super-user accounts are kept separate and privileges are re-evaluated on a recurring basis?', 'C1.05', null, 'Identity and Access Management', 'C1', 'IAM', 'The WhiskeySAML tool automates the remote extraction of an ADFS signing certificate.', 'Secureworks WhiskeySAML', 'tool', 'https://github.com/secureworks/whiskeysamlandfriends'),
        ('u_unique_svc_accounts', 'Do you ensure all credentials, including those for service/machine accounts, are unique and separate across IT and OT networks?', 'C1.06', 'Service account: "Non-human" account often used by an application or service to interact with the operating system.', 'Identity and Access Management', 'C1', 'IAM', 'To prevent a security incident in one of your accounts from affecting all of your accounts, it''s important to use unique passwords. Check out this article to learn more.', 'Choosing and Protecting Passwords', 'article', 'https://www.cisa.gov/news-events/news/choosing-and-protecting-passwords'),
        ('u_unique_svc_accounts', 'Do you ensure all credentials, including those for service/machine accounts, are unique and separate across IT and OT networks?', 'C1.06', 'Service account: "Non-human" account often used by an application or service to interact with the operating system.', 'Identity and Access Management', 'C1', 'IAM', 'This tool is a username enumeration and password spraying tool aimed at Microsoft Office 365.', 'O365Spray', 'tool', 'https://github.com/0xZDH/o365spray'),
        ('u_departing_employee_return', 'Do you have an enforced process that ensures all departing employees return their physical security badges, tokens, etc. and have their accesses revoked on the day of their departure?', 'C1.07', null, 'Identity and Access Management', 'C1', 'IAM', 'Employees who leave your organization should not have access to your organization''s data. Watch this webinar to learn more about departing employees and other potential insider threats.', 'A Holistic Approach to Mitigating Insider Threats', 'video', 'https://www.youtube.com/watch?v=IlNT0uJOZeg'),
        ('u_departing_employee_return', 'Do you have an enforced process that ensures all departing employees return their physical security badges, tokens, etc. and have their accesses revoked on the day of their departure?', 'C1.07', null, 'Identity and Access Management', 'C1', 'IAM', 'This guide will explain the threat that current and former employees can pose to your organization and offer to steps to mitigate the risk.', 'Insider Threat Mitigation Guide', 'publication', 'https://www.cisa.gov/sites/default/files/2022-11/Insider%20Threat%20Mitigation%20Guide_Final_508.pdf'),
        ('u_hw_software_firmware_approval', 'Do you have administrative policies or automated processes that ensure all new hardware, firmware or software must be approved before being deployed?', 'C2.01', null, 'Device Configuration and Security', 'C2', 'Devices', 'This tool is designed to help identify devices and applications. The spreadsheet can be used to track hardware, software, and sensitive information.', 'CIS Hardware and Software Asset Tracker', 'tool', 'https://www.cisa.gov/resources-tools/resources/free-cybersecurity-services-and-tools#:~:text=https%3A//www.cisecurity.org/white%2Dpapers/cis%2Dhardware%2Dand%2Dsoftware%2Dasset%2Dtracking%2Dspreadsheet/'),
        ('u_hw_software_firmware_approval', 'Do you have administrative policies or automated processes that ensure all new hardware, firmware or software must be approved before being deployed?', 'C2.01', null, 'Device Configuration and Security', 'C2', 'Devices', 'In order to keep your environment secure, you have to know what devices you have, how they''re configured, and have a defined process for any changes you need to make. Read this guide to Configuration and Change Management to get started.', 'Configuration and Change Management CRR', 'guide', 'https://www.cisa.gov/sites/default/files/c3vp/crr_resources_guides/CRR_Resource_Guide-CCM.pdf'),
        ('u_macros_disabled', 'Are Microsoft Office macros, or similar embedded code, disabled by default on all devices?', 'C2.02', 'Microsoft Office Macros: A macro in Access is a tool that automates tasks and adds functionality to forms, reports, and controls. For example, when a command button is added to a form, the button’s OnClick event is associated with the macro.', 'Device Configuration and Security', 'C2', 'Devices', 'Many types of malware rely on embedded code, such as Microsoft Office macros. To keep your organization safe, these macros should be disabled by default. Read this article to learn more.', 'Macro Security For Microsoft Office', 'article', 'https://www.ncsc.gov.uk/guidance/macro-security-for-microsoft-office'),
        ('u_macros_disabled', 'Are Microsoft Office macros, or similar embedded code, disabled by default on all devices?', 'C2.02', 'Microsoft Office Macros: A macro in Access is a tool that automates tasks and adds functionality to forms, reports, and controls. For example, when a command button is added to a form, the button’s OnClick event is associated with the macro.', 'Device Configuration and Security', 'C2', 'Devices', 'This white paper from the Center for Internet Security will walk you through the process of disabling macros by default in your organization.', 'How to Disable Macros', 'guide', 'https://www.cisecurity.org/insights/white-papers/intel-insight-how-to-disable-macros'),
        ('u_asset_inventory', 'Do you maintain a regularly updated inventory of all organizational assets with an IP address, and update the inventory on a recurring basis?', 'C2.03', 'Inventory: The formal listing or property record of personal property assigned to an organization.', 'Device Configuration and Security', 'C2', 'Devices', 'This tool helps users strengthen their security posture by evaluating their security and data attack surface; providing asset inventory and discovery; identifying misconfigurations, vulnerabilities and threats; and helping them mitigate and remediate risks.', 'Google Security Command Center', 'tool', 'https://cloud.google.com/security/products/security-command-center'),
        ('u_asset_inventory', 'Do you maintain a regularly updated inventory of all organizational assets with an IP address, and update the inventory on a recurring basis?', 'C2.03', 'Inventory: The formal listing or property record of personal property assigned to an organization.', 'Device Configuration and Security', 'C2', 'Devices', 'What do you know about your internet attack surface? To make sure you know what''s accessible to attackers, check out CISA''s Stuff Off Search.', 'Stuff Off Search', 'resource', 'https://www.cisa.gov/resources-tools/resources/stuff-search'),
        ('u_prohibit_unauth_devices', 'Do you have policies and processes to prohibit the connection of unauthorized devices and media to IT and OT systems?', 'C2.04', 'Information Technology (IT) and Operational Technology (OT): Detailed definitions and distinctions between IT and OT, emphasizing the prohibition of unauthorized devices.', 'Device Configuration and Security', 'C2', 'Devices', 'Keep your organization safe by ensuring you have policies and procedures to prevent unauthorized devices from connecting to your network. This article outlines the risks posed by portable devices.', 'The Risks of Portable Devices', 'publication', 'https://www.cisa.gov/sites/default/files/publications/RisksOfPortableDevices.pdf'),
        ('u_prohibit_unauth_devices', 'Do you have policies and processes to prohibit the connection of unauthorized devices and media to IT and OT systems?', 'C2.04', 'Information Technology (IT) and Operational Technology (OT): Detailed definitions and distinctions between IT and OT, emphasizing the prohibition of unauthorized devices.', 'Device Configuration and Security', 'C2', 'Devices', 'Read this blog from CISA to learn about how to protect your portable devices.', 'Protecting Portable Devices', 'article', 'https://www.cisa.gov/news-events/news/protecting-portable-devices-data-security'),
        ('u_network_diagrams', 'Do you maintain accurate documentation of network topology for all IT and OT networks?', 'C2.05', 'Network topology is used to describe the physical and logical structure of a network. It maps the way different nodes on a network--including switches and routers--are placed and interconnected, as well as how data flows. Information Technology (IT): Any equipment or interconnected system or subsystem of equipment used in the automatic acquisition, storage, analysis, evaluation, manipulation, management, movement, control, display, switching, interchange, transmission, or reception of data or information. Operational Technology (OT): Programmable systems or devices that interact with the physical environment (or manage devices that interact with the physical environment). These systems/devices detect or cause a direct change through the monitoring and/or control of devices, processes, and events. Examples include ICSs, building management systems, fire control systems, and physical access control mechanisms.', 'Device Configuration and Security', 'C2', 'Devices', 'To know what to protect, you need to know what you have. Check out this resource guide to creating an asset inventory.', 'Asset Inventory', 'guide', 'https://www.cisa.gov/sites/default/files/c3vp/crr_resources_guides/CRR_Resource_Guide-AM.pdf'),
        ('u_network_diagrams', 'Do you maintain accurate documentation of network topology for all IT and OT networks?', 'C2.05', 'Network topology is used to describe the physical and logical structure of a network. It maps the way different nodes on a network--including switches and routers--are placed and interconnected, as well as how data flows. Information Technology (IT): Any equipment or interconnected system or subsystem of equipment used in the automatic acquisition, storage, analysis, evaluation, manipulation, management, movement, control, display, switching, interchange, transmission, or reception of data or information. Operational Technology (OT): Programmable systems or devices that interact with the physical environment (or manage devices that interact with the physical environment). These systems/devices detect or cause a direct change through the monitoring and/or control of devices, processes, and events. Examples include ICSs, building management systems, fire control systems, and physical access control mechanisms.', 'Device Configuration and Security', 'C2', 'Devices', 'This video from Microsoft explains how to use Microsoft Vizio to create a network diagram', 'Create a Network Diagram', 'video', 'https://support.microsoft.com/en-us/office/video-create-a-network-diagram-a2360cd9-5c9d-4839-b4f6-17b485e02262'),
        ('u_basline_config_documents', 'Do you maintain accurate documentation describing the baseline and current configuration details of all critical IT and OT assets?', 'C2.06', 'Baseline configurations: A documented set of specifications for an information system, or a configuration item within a system, that has been formally reviewed and agreed on at a given point in time, and which can be changed only through change control procedures. Detailed definitions of IT and OT included.', 'Device Configuration and Security', 'C2', 'Devices', 'This toolset allows enterprise security administrators to download, analyze, test, edit and store Microsoft-recommended security configuration baselines for Windows and other Microsoft products, while comparing them against other security configurations. ', 'Microsoft Security Compliance Toolkit 1.0', 'tool', 'https://www.microsoft.com/en-us/download/details.aspx?id=55319'),
        ('u_basline_config_documents', 'Do you maintain accurate documentation describing the baseline and current configuration details of all critical IT and OT assets?', 'C2.06', 'Baseline configurations: A documented set of specifications for an information system, or a configuration item within a system, that has been formally reviewed and agreed on at a given point in time, and which can be changed only through change control procedures. Detailed definitions of IT and OT included.', 'Device Configuration and Security', 'C2', 'Devices', 'In order to keep your environment secure, you have to know what devices you have, how they''re configured, and have a defined process for any changes you need to make. Read this guide to Configuration and Change Management to get started.', 'Configuration and Change Management', 'guide', 'https://www.cisa.gov/sites/default/files/publications/CRR_Resource_Guide-CCM_0.pdf'),
        ('u_log_storage', 'Are logs stored in a secure, centralized system, such as a security information and event management (SIEM) tool?', 'C3.01', 'Security information and event management (SIEM) tools: solutions which aggregate logs and allow users to create rules in order to detect, analyze, and respond to security threats. Logs: A record of the events occurring within an organization’s systems and networks.', 'Data Security', 'C3', 'Data', 'Logging is an important part of any organization''s security posture. CISA has rolled out a new service that will make logging a breeze for your organization. Click the link to learn more!', 'Logging Made Easy (LME)', 'tool', 'https://www.cisa.gov/resources-tools/services/logging-made-easy'),
        ('u_log_storage', 'Are logs stored in a secure, centralized system, such as a security information and event management (SIEM) tool?', 'C3.01', 'Security information and event management (SIEM) tools: solutions which aggregate logs and allow users to create rules in order to detect, analyze, and respond to security threats. Logs: A record of the events occurring within an organization’s systems and networks.', 'Data Security', 'C3', 'Data', 'Watch this webinar to learn about the importance of logging and how logs can be used in incident analysis and response.', 'Introduction to Investigating Logs for Incidents', 'video', 'https://www.youtube.com/watch?v=pAE4hHdBI4Q'),
        ('u_log_storage_detect_resp', 'Do you collect and store logs for use of both detection and incident response activities?', 'C3.02', 'Logs: A record of the events occurring within an organization’s systems and networks.', 'Data Security', 'C3', 'Data', 'Watch this webinar to learn about incident response tools.', 'Introduction to Incident Analysis and Tools', 'video', 'https://www.youtube.com/watch?v=0m7NN6yvsq0'),
        ('u_log_storage_detect_resp', 'Do you collect and store logs for use of both detection and incident response activities?', 'C3.02', 'Logs: A record of the events occurring within an organization’s systems and networks.', 'Data Security', 'C3', 'Data', 'Security Onion is a free and open Linux distribution for threat hunting, enterprise security monitoring, and log management.', 'Security Onion', 'tool', 'https://securityonionsolutions.com/software'),
        ('u_connect_deny_default', 'Do you ensure all connections between IT and OT assets are denied by default unless explicitly allowed, and are required to pass through an intermediary system, which is monitored and performs log collection?', 'C3.03', 'Demilitarized Zone (DMZ), Firewall, IT, OT: Detailed definitions and importance of ensuring strict connectivity rules and monitoring.', 'Data Security', 'C3', 'Data', 'Check out this infographic to learn more about layering network security through segmentation.', 'Layering Network Security through Segmentation Infographic', 'publication', 'https://www.cisa.gov/sites/default/files/publications/layering-network-security-segmentation_infographic_508_0.pdf'),
        ('u_connect_deny_default', 'Do you ensure all connections between IT and OT assets are denied by default unless explicitly allowed, and are required to pass through an intermediary system, which is monitored and performs log collection?', 'C3.03', 'Demilitarized Zone (DMZ), Firewall, IT, OT: Detailed definitions and importance of ensuring strict connectivity rules and monitoring.', 'Data Security', 'C3', 'Data', 'Visit Carnegie Mellon University''s Software Engineering Institute Blog for an article on Network Segmentation concepts.', 'Network Segmentation: Concepts and Practices', 'blog', 'https://insights.sei.cmu.edu/blog/network-segmentation-concepts-and-practices/'),
        ('u_secure_credential_storage', 'Are sensitive data, including credentials, stored in a secure manner and only accessible to authenticated and authorized users?', 'C3.04', null, 'Data Security', 'C3', 'Data', 'To make sure that you are properly managing user identities and credentials, check out this guide.', 'Identity, Credential, and Access Management (ICAM) ', 'guide', 'https://www.cisa.gov/sites/default/files/2023-02/ICAM_Reference_Guide_FINAL_508.pdf'),
        ('u_secure_credential_storage', 'Are sensitive data, including credentials, stored in a secure manner and only accessible to authenticated and authorized users?', 'C3.04', null, 'Data Security', 'C3', 'Data', 'This tool encrypts Microsoft Windows systems.', 'BitLocker for Microsoft Windows', 'tool', 'https://learn.microsoft.com/en-us/windows/security/operating-system-security/data-protection/bitlocker/install-server'),
        ('u_tls_enabled', 'Do you employ properly configured and up-to-date Transport Layer Security to protect data in transit whenever feasible?', 'C3.05', 'Transport Layer Security (TLS) explanation and the importance of protecting data in transit.', 'Data Security', 'C3', 'Data', 'To protect data in transit, check out this Guide from the Center for Internet Security.', 'Encypt Data in Transit', 'guide', 'https://essentialguide.docs.cisecurity.org/en/latest/bp/encrypt_data_in_transit.html'),
        ('u_tls_enabled', 'Do you employ properly configured and up-to-date Transport Layer Security to protect data in transit whenever feasible?', 'C3.05', 'Transport Layer Security (TLS) explanation and the importance of protecting data in transit.', 'Data Security', 'C3', 'Data', 'SSL (Secure Socket Layer) is the standard security technology for establishing an encrypted link between a web server and a browser. Cloudflare allows any internet property to use SSL with the click of a button.', 'Cloudflare Universal Secure Socket Layer Certificate', 'service', 'https://www.cloudflare.com/plans/free/'),
        ('u_email_tls_dkim', 'Do you implement STARTTLS, SPF, DKIM, and DMARC on all organizational email infrastructure?', 'C3.06', 'Explanation of STARTTLS, SPF, DKIM, and DMARC for email security and their role in protecting against spoofed email.', 'Data Security', 'C3', 'Data', 'A significant portion of attacks against organizations come via email. Download this guide to CISA''s recommendations for enhancing email security to protect your organization.', 'Enhance Email and Web Security', 'guide', 'https://www.cisa.gov/sites/default/files/publications/CISAInsights-Cyber-EnhanceEmailandWebSecurity_S508C.pdf'),
        ('u_email_tls_dkim', 'Do you implement STARTTLS, SPF, DKIM, and DMARC on all organizational email infrastructure?', 'C3.06', 'Explanation of STARTTLS, SPF, DKIM, and DMARC for email security and their role in protecting against spoofed email.', 'Data Security', 'C3', 'Data', 'Perception Point.	Perception Point''s Free Email Security Plan, protects organizations from any threat entering organization via email and other collaboration channels. ', 'Perception Point', 'service', 'https://perception-point.io/advanced-email-security-contact-us/'),
        ('u_ttp_list', 'Do you maintain a regularly updated list of threats and their Tactics, Techniques, and Procedures (TTPs; for example, MITRE ATT&CK) relevant to your organization?', 'C3.07', 'TTPs, The MITRE ATT&CK framework: Explaining the importance of understanding and updating the list of potential threats and their methodologies.', 'Data Security', 'C3', 'Data', 'CISA regularly publishes alerts and adviseries to keep organizations informed about existing and potential threats.', 'CISA''s Alerts and Adversaries', 'alerts', 'https://www.cisa.gov/news-events/cybersecurity-advisories'),
        ('u_ttp_list', 'Do you maintain a regularly updated list of threats and their Tactics, Techniques, and Procedures (TTPs; for example, MITRE ATT&CK) relevant to your organization?', 'C3.07', 'TTPs, The MITRE ATT&CK framework: Explaining the importance of understanding and updating the list of potential threats and their methodologies.', 'Data Security', 'C3', 'Data', 'This tool protects and detects endpoint threats, including file-based and fileless malware. Built into Windows 10 and 11 and in versions of Windows Server.', 'Microsoft Defender Antivirus', 'tool', 'https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows?view=o365-worldwide'),
        ('u_named_cyber_role', 'Does your organization have a named role/position/title identified as responsible and accountable for planning, resourcing, and execution of cybersecurity activities?', 'C4.01', null, 'Governance and Training', 'C4', 'Governance', 'CISA''s Cyber Essentials is a guide for leaders of small organizations to develop an actionable understanding of where to start implementing organizational cybersecurity practices.', 'CISA Cyber Essentials Starter Kit', 'guide', 'https://www.cisa.gov/sites/default/files/publications/Cyber%2520Essentials%2520Starter%2520Kit_03.12.2021_508_0.pdf'),
        ('u_named_cyber_role', 'Does your organization have a named role/position/title identified as responsible and accountable for planning, resourcing, and execution of cybersecurity activities?', 'C4.01', null, 'Governance and Training', 'C4', 'Governance', 'To get started implementing a security culture at your organization, take a look at CISA''s Guidance for Small Organizations.', 'Cyber Guidance for Beginners', 'resource', 'https://www.cisa.gov/cyber-guidance-small-businesses'),
        ('u_annual_cyber_training', 'Are all employees and contractors provided with basic cybersecurity training on at least an annual basis?', 'C4.02', null, 'Governance and Training', 'C4', 'Governance', 'Did you know that CISA is on YouTube? Check out our channel for short educational videos like this one that you can use to train your employees and increase their security awareness.', 'Recognize and Report Phishing Video', 'video', 'https://www.youtube.com/watch?v=JlQovysQBn0'),
        ('u_annual_cyber_training', 'Are all employees and contractors provided with basic cybersecurity training on at least an annual basis?', 'C4.02', null, 'Governance and Training', 'C4', 'Governance', 'You can find plenty of documents providing basic cybersecurity guidance for your employees at cisa.gov, including this article detailing Anti-phishing guidance for your organizaiton.', 'Stopping the Attack Cycle at Phase One', 'article', 'https://www.cisa.gov/sites/default/files/2023-10/Phishing%20Guidance%20-%20Stopping%20the%20Attack%20Cycle%20at%20Phase%20One_508c.pdf'),
        ('u_ot_cyber_training', 'Do you have training for operational technology (OT) cybersecurity?', 'C4.03', 'Operational Technology (OT): Programmable systems or devices that interact with the physical environment. Examples include ICSs, building management systems, fire control systems, and physical access control mechanisms. Importance of specialized cybersecurity training for OT.', 'Governance and Training', 'C4', 'Governance', 'Did you know that CISA provides virtual and in-person training sessions on a variety of topics? Visit CISA''s training page to learn more.', 'OT Training Sign Up', 'training', 'https://www.cisa.gov/resources-tools/training'),
        ('u_ot_cyber_training', 'Do you have training for operational technology (OT) cybersecurity?', 'C4.03', 'Operational Technology (OT): Programmable systems or devices that interact with the physical environment. Examples include ICSs, building management systems, fire control systems, and physical access control mechanisms. Importance of specialized cybersecurity training for OT.', 'Governance and Training', 'C4', 'Governance', 'This Guide helps professionals develop a training plan based on their current skill level and desired career opportunities.', 'Cybersecurity Workforce Training Guide', 'guide', 'https://www.cisa.gov/sites/default/files/publications/Cybersecurity%2520Workforce%2520Training%2520Guide%25207.28.21%2520508c.pdf'),
        ('u_kev_mitagation', 'Do you keep track of known exploited vulnerabilities (listed in CISA’s KEV Catalog) and ensure they are patched or mitigated in a timely fashion?', 'C5.01', 'Known Exploitable Vulnerabilities (KEV) Catalog: A list of vulnerabilities that CISA has identified as being exploited, or that have been used by threat actors.', 'Vulnerability Management', 'C5', 'VM', 'Many software updates are created to fix security risks, so it''s important to keep your software up to date, as this blog article will explain.', 'Understanding Patches and Software Updates', 'blog', 'https://www.cisa.gov/news-events/news/understanding-patches-and-software-updates'),
        ('u_kev_mitagation', 'Do you keep track of known exploited vulnerabilities (listed in CISA’s KEV Catalog) and ensure they are patched or mitigated in a timely fashion?', 'C5.01', 'Known Exploitable Vulnerabilities (KEV) Catalog: A list of vulnerabilities that CISA has identified as being exploited, or that have been used by threat actors.', 'Vulnerability Management', 'C5', 'VM', 'CISA keeps a database on Known Exploited Vulnerabilities on our website. Check it out here.', 'Known Exploited Vulnerabilities', 'resource', 'https://www.cisa.gov/known-exploited-vulnerabilities-catalog'),
        ('u_security_research_contact', 'Do you maintain a public, easily discoverable method (such as a security.txt file) for security researchers to notify your security team of vulnerable, misconfigured, or otherwise exploitable assets?', 'C5.02', 'Vulnerability Disclosure Program: Gives security researchers clear guidelines for conducting vulnerability discovery activities and conveys preferences for submitting discovered vulnerabilities to an organization. security.txt file: a proposed standard for websites security information meant to allow security researchers to easily report security vulnerabilities.', 'Vulnerability Management', 'C5', 'VM', 'Visit https://securitytxt.org/ to learn about how you can create your owen security.txt file.', 'CISA VDP', 'service', 'https://www.cisa.gov/resources-tools/services/vulnerability-disclosure-policy-vdp-platform'),
        ('u_security_research_contact', 'Do you maintain a public, easily discoverable method (such as a security.txt file) for security researchers to notify your security team of vulnerable, misconfigured, or otherwise exploitable assets?', 'C5.02', 'Vulnerability Disclosure Program: Gives security researchers clear guidelines for conducting vulnerability discovery activities and conveys preferences for submitting discovered vulnerabilities to an organization. security.txt file: a proposed standard for websites security information meant to allow security researchers to easily report security vulnerabilities.', 'Vulnerability Management', 'C5', 'VM', 'Visit https://securitytxt.org/ to learn about how you can create your owen security.txt file.', 'securitytxt.org', 'tool', 'https://securitytxt.org'),
        ('u_public_services_disabled', 'Do you ensure that no exploitable services, such as Remote Desktop Protocol (RDP), are exposed on the public internet without appropriate compensating controls?', 'C5.03', 'Remote Desktop Protocol (RDP): Microsoft proprietary protocol explanation and the importance of not exposing exploitable services without compensating controls.', 'Vulnerability Management', 'C5', 'VM', 'CISA''s Cyber Hygiene Web Application Scanning is "internet scanning-as-a-service." This service assesses the "health" of your publicly accessible web applications by checking for known vulnerabilities and weak configurations.', 'Web Application Scanning Service', 'article', 'https://www.cisa.gov/news-events/news/cyber-hygiene-web-application-scanning'),
        ('u_public_services_disabled', 'Do you ensure that no exploitable services, such as Remote Desktop Protocol (RDP), are exposed on the public internet without appropriate compensating controls?', 'C5.03', 'Remote Desktop Protocol (RDP): Microsoft proprietary protocol explanation and the importance of not exposing exploitable services without compensating controls.', 'Vulnerability Management', 'C5', 'VM', 'This tool continuously collects and correlates data from internet accessible devices, allowing organizations to see what is their attack surface and what they are exposing to attackers. ', 'Binary Edge', 'tool', 'https://www.binaryedge.io'),
        ('u_no_public_devices', 'Do you ensure that no OT assets are on the public Internet, except where explicitly required for operation and protected by appropriate compensating controls?', 'C5.04', 'Operational Technology (OT) explanation and the emphasis on protecting OT assets from public Internet exposure, except under protected conditions.', 'Vulnerability Management', 'C5', 'VM', 'Did you know that CISA offers several cyber hygiene services to help keep your organization safe? Visit the Vulnerability Scanning page today to take advantage of this free service.', 'Cyber Hygiene Vulnerability Scanning', 'resource', 'https://www.cisa.gov/cyber-resource-hub'),
        ('u_no_public_devices', 'Do you ensure that no OT assets are on the public Internet, except where explicitly required for operation and protected by appropriate compensating controls?', 'C5.04', 'Operational Technology (OT) explanation and the emphasis on protecting OT assets from public Internet exposure, except under protected conditions.', 'Vulnerability Management', 'C5', 'VM', 'CISA''s Cyber Hygiene Web Application Scanning is "internet scanning-as-a-service." This service assesses the "health" of your publicly accessible web applications by checking for known vulnerabilities and weak configurations.', 'Web Application Scanning Service', 'article', 'https://www.cisa.gov/news-events/news/cyber-hygiene-web-application-scanning'),
        ('u_3rd_party_cyber_validation', 'Do third-parties with demonstrated expertise in (IT and/or OT) cybersecurity regularly validate the effectiveness and coverage of your cybersecurity defenses?', 'C5.05', 'Explanation of the role of third-party validations in ensuring the effectiveness and coverage of cybersecurity defenses.', 'Vulnerability Management', 'C5', 'VM', 'This service tests perimeter defenses by mimicking the techniques adversaries use to gain unauthorized access to networks', 'Remote Penetration Test Service', 'service', 'https://www.cisa.gov/stopransomware/services'),
        ('u_3rd_party_cyber_validation', 'Do third-parties with demonstrated expertise in (IT and/or OT) cybersecurity regularly validate the effectiveness and coverage of your cybersecurity defenses?', 'C5.05', 'Explanation of the role of third-party validations in ensuring the effectiveness and coverage of cybersecurity defenses.', 'Vulnerability Management', 'C5', 'VM', 'CISA offers a wide portfolio of downloadable Tabletop Exercise Packages (CTEPs) to serve as an off-the-shelf solution for a variety of stakeholders'' exercise needs', 'Stakeholder Exercises', 'service', 'https://www.cisa.gov/resources-tools/services/stakeholder-exercises'),
        ('u_security_inc_sla', 'Do your procurement documents and contracts require vendors and service providers to inform you of security incidents within a certain time frame?', 'C6.01', 'Procurement Documents: the paperwork detailing the contractual relationship between a customer and a supplier of goods or services', 'Supply Chain Risk Management', 'C6', 'SCRM', 'Download CISA''s Third Party Risk Management template, so you can start making sure your third parties don''t pose unnecessary risk to your organization', 'Third Party Risk Management Template', 'publication', 'https://www.cisa.gov/sites/default/files/publications/ICTSCRMTF_Vendor-SCRM-Template_508.pdf'),
        ('u_security_inc_sla', 'Do your procurement documents and contracts require vendors and service providers to inform you of security incidents within a certain time frame?', 'C6.01', 'Procurement Documents: the paperwork detailing the contractual relationship between a customer and a supplier of goods or services', 'Supply Chain Risk Management', 'C6', 'SCRM', 'This free online course is available to the public and will explain how to get started with Supply Chain Risk Management', 'Cyber Supply Chain Risk Management for the Public', 'course', 'https://fedvte.usalearning.gov/publiccourses/cscrm/index.htm'),
        ('u_security_vuln_sla', 'Do your procurement documents and contracts require vendors and service providers to inform you of security vulnerabilities within a certain time frame?', 'C6.02', 'Procurement Documents: the paperwork detailing the contractual relationship between a customer and a supplier of goods or services', 'Supply Chain Risk Management', 'C6', 'SCRM', 'The ICT SCRM Task Force''s resource guide was created to provide a valuable starting point for you to develop and tailor an ICT SCRM plan that meets the needs of your organization.', 'A Resource Guide for developing a Resilient Supply Chain Risk Management Plan', 'guide', 'https://www.cisa.gov/sites/default/files/2023-10/Empowering%20SMBs%20-%20A%20Resource%20Guide%20For%20Developing%20A%20Resilient%20SCRM%20Plan_508_0.pdf'),
        ('u_security_vuln_sla', 'Do your procurement documents and contracts require vendors and service providers to inform you of security vulnerabilities within a certain time frame?', 'C6.02', 'Procurement Documents: the paperwork detailing the contractual relationship between a customer and a supplier of goods or services', 'Supply Chain Risk Management', 'C6', 'SCRM', 'This handbook provides an overview of the highest supply chain risk categories commonly faced by ICT small and medium-sized businesses (SMBs).', 'Securing Small and Medium-Sized Business (SMB) Supply Chains: A Resource Handbook', 'handbook', 'https://www.cisa.gov/sites/default/files/2023-01/Securing-SMB-Supply-Chains_Resource-Handbook_508.pdf'),
        ('u_vendor_eval_docs', 'Do your procurements documents outline cybersecurity requirements and questions that are used to evaluate vendors such that, given two roughly equivalent options based on cost and functionality, the more secure option is preferred?', 'C6.03', 'Procurement Documents: the paperwork detailing the contractual relationship between a customer and a supplier of goods or services', 'Supply Chain Risk Management', 'C6', 'SCRM', 'When choosing a vendor, it''s important to keep security in mind. Watch this video to learn how to evaluate a vendor''s trustworthiness.', 'Evaluating Vendor and Supplier Trustworthiness', 'video', 'https://www.youtube.com/watch?v=bf_M_47BNkw'),
        ('u_vendor_eval_docs', 'Do your procurements documents outline cybersecurity requirements and questions that are used to evaluate vendors such that, given two roughly equivalent options based on cost and functionality, the more secure option is preferred?', 'C6.03', 'Procurement Documents: the paperwork detailing the contractual relationship between a customer and a supplier of goods or services', 'Supply Chain Risk Management', 'C6', 'SCRM', 'Security Scorecards is a collection of security health metrics for open source, allowing users to evaluate the security practices of an open source package before use.', 'OpenSSF: Scorecards', 'tool', 'https://github.com/ossf/scorecard'),
        ('u_asset_recovery_plan', 'Do you have up-to-date plans to recover and restore assets in case of a cybersecurity incident?', 'C7.01', null, 'Incident Response', 'C7', 'IR', 'To get started making an Incident Response plan, check out CISA''s free on-demand webinar "Incident Response and Awareness Training"', 'Incident Response Webinar', 'training', 'https://www.cisa.gov/resources-tools/training/incident-response-and-awareness-training'),
        ('u_asset_recovery_plan', 'Do you have up-to-date plans to recover and restore assets in case of a cybersecurity incident?', 'C7.01', null, 'Incident Response', 'C7', 'IR', 'The The Cyber Resilience Review Resource Guide for Incident Management has an Incident Reponse Plan Template that you can use to start drafting an IRP for your organization.', 'CRR Supplemental Resource Guide, Volume 5: Incident Management - Appendix A: Template', 'publication', 'https://www.cisa.gov/sites/default/files/c3vp/crr_resources_guides/CRR_Resource_Guide-IM.pdf'),
        ('u_cyber_incident_plan', 'Do you have up-to-date cybersecurity incident plans for both IT and OT, and are these Incident Response plans drilled at least annually?', 'C7.02', 'Information Technology (IT) and Operational Technology (OT): Definitions and the importance of having incident response plans for both, including annual drills.', 'Incident Response', 'C7', 'IR', 'Check out this fact sheet for some tips on creating and running your own tabletop exercises.', 'Cybersecurity Tabletop Exercise Tips ', 'publication', 'https://www.cisa.gov/sites/default/files/publications/Cybersecurity-Tabletop-Exercise-Tips_508c.pdf'),
        ('u_cyber_incident_plan', 'Do you have up-to-date cybersecurity incident plans for both IT and OT, and are these Incident Response plans drilled at least annually?', 'C7.02', 'Information Technology (IT) and Operational Technology (OT): Definitions and the importance of having incident response plans for both, including annual drills.', 'Incident Response', 'C7', 'IR', 'CISA offers a wide portfolio of downloadable Tabletop Exercise Packages (CTEPs) to serve as an off-the-shelf solution for a variety of stakeholders'' exercise needs', 'Tabletop Exercise Packages', 'service', 'https://www.cisa.gov/resources-tools/services/cisa-tabletop-exercise-packages'),
        ('u_inc_reporting_policy', 'Do you have codified policies and procedures that specify to whom and how to report all confirmed cybersecurity incidents to the appropriate external authorities, within time frames directed by applicable regulatory guidance?', 'C7.03', null, 'Incident Response', 'C7', 'IR', 'Save this link - The CISA Incident Reporting System provides a secure web-enabled means of reporting computer security incidents to CISA.', 'CISA''s Incident Reporting System', 'form', 'https://www.cisa.gov/forms/report'),
        ('u_inc_reporting_policy', 'Do you have codified policies and procedures that specify to whom and how to report all confirmed cybersecurity incidents to the appropriate external authorities, within time frames directed by applicable regulatory guidance?', 'C7.03', null, 'Incident Response', 'C7', 'IR', 'This document provides guidance on incident reporting requirements.', 'Federal Incident Notification Guidelines', 'publication', 'https://www.cisa.gov/sites/default/files/publications/Federal_Incident_Notification_Guidelines.pdf'),
        ('u_regular_backups', 'Do you back up all business critical systems at a regular cadence, no less than once per year, and are these backups stored separately from the source systems?', 'C7.04', null, 'Incident Response', 'C7', 'IR', 'To ensure the availabilty of your data, it''s important to make regular backups.  This guidline from CISA outlines some options for how to backup your data.', 'Data Backup Options', 'publication', 'https://www.cisa.gov/sites/default/files/publications/data_backup_options.pdf'),
        ('u_regular_backups', 'Do you back up all business critical systems at a regular cadence, no less than once per year, and are these backups stored separately from the source systems?', 'C7.04', null, 'Incident Response', 'C7', 'IR', 'This tool sets up automatic backups of Windows 10 and 11 operating systems.', 'Windows Auto Backup', 'tool', 'https://support.microsoft.com/en-us/windows/back-up-your-windows-pc-87a81f8a-78fa-456e-b521-ac0560e32338')
)
   , c as (
    insert into category (name, number, "shortName")
        select distinct "categoryName" as name, "categoryNumber" as number, "shortName"
        from data
        order by number
        on conflict ("number") do nothing
        returning id, number
)
   , q as (
    insert into question (name, "longForm", number, "categoryId", description)
        select distinct "questionName" as name, "longForm", "questionNumber" as number, (select id from c where c.number = "categoryNumber") as "categoryId", "questionDescription" as description
        from data
        order by number
        returning id, name
)
   , r as (
    insert into resource (description, name, type, url)
        select distinct "resourceDescription" as description, "resourceName" as name, type, url
        from data
        where url is not null
        returning id, url
)
insert into question_resources_resource ("questionId", "resourceId")
select
    q.id as "questionId",
    r.id as "resourceId"
from q
         join data d on q.name = d."questionName"
         join r on d.url = r.url;

-- Populates a sample assessment and associates it with the user with the email address specified in the constants CTE
with constants as (
    select
        '2024-03-19 02:47:43.000000' as "createdAt",
        '8adc82fb-5d82-4804-ad82-3b82a38fe67c' as "rscId",
        'micro_to_small' as type,
        'user@mail.com'  as email -- Change 'user@mail.com' to the email address of the user you want to associate the assessment with
)
   ,data(name, selection) as (
        values
            ('u_it_org_size', 'micro_to_small'),
            ('u_pw_different', 'Yes'),
            ('u_pw_strong', 'Yes'),
            ('u_mfa_enabled', 'Yes'),
            ('u_backup_data', 'Yes'),
            ('u_backup_method', 'An external hard drive'),
            ('u_backup_auto', 'Yes'),
            ('u_backup_access', 'Yes'),
            ('u_device_type', 'mobile_device'),
            ('u_security_features', 'Yes'),
            ('u_fw_av', 'Yes'),
            ('u_disable_svcs', 'Yes'),
            ('u_software_updates', 'Yes'),
            ('u_reputable_software', 'always'),
            ('u_iam_security', 'In Progress'),
            ('u_device_config', 'Scoped'),
            ('u_cia_data', 'Implemented'),
            ('u_governance_training', 'Implemented'),
            ('u_vul_management', 'In Progress'),
            ('u_supply_chain_risk', 'Implemented'),
            ('u_inc_response_plan', 'Not Started'),
            ('u_pw_length', 'Not Started'),
            ('u_log_unsuccessful_login', 'Scoped'),
            ('u_connect_deny_default', 'Implemented'),
            ('u_secure_credential_storage', 'Not Started'),
            ('u_tls_enabled', 'Implemented'),
            ('u_change_default_pw', 'Scoped'),
            ('u_strong_mfa', 'Not Started'),
            ('u_separate_admin', 'Scoped'),
            ('u_unique_svc_accounts', 'In Progress'),
            ('u_departing_employee_return', 'Implemented'),
            ('u_hw_software_firmware_approval', 'Not Started'),
            ('u_macros_disabled', 'Implemented'),
            ('u_asset_inventory', 'Implemented'),
            ('u_prohibit_unauth_devices', 'In Progress'),
            ('u_network_diagrams', 'Scoped'),
            ('u_basline_config_documents', 'Scoped'),
            ('u_log_storage', 'Implemented'),
            ('u_log_storage_detect_resp', 'Scoped'),
            ('u_email_tls_dkim', 'In Progress'),
            ('u_ttp_list', 'Implemented'),
            ('u_named_cyber_role', 'Implemented'),
            ('u_annual_cyber_training', 'Scoped'),
            ('u_ot_cyber_training', 'Implemented'),
            ('u_kev_mitagation', 'Implemented'),
            ('u_security_research_contact', 'In Progress'),
            ('u_public_services_disabled', 'Implemented'),
            ('u_no_public_devices', 'In Progress'),
            ('u_3rd_party_cyber_validation', 'In Progress'),
            ('u_security_inc_sla', 'Scoped'),
            ('u_security_vuln_sla', 'Implemented'),
            ('u_vendor_eval_docs', 'Scoped'),
            ('u_asset_recovery_plan', 'Scoped'),
            ('u_cyber_incident_plan', 'Scoped'),
            ('u_inc_reporting_policy', 'In Progress'),
            ('u_regular_backups', 'Implemented')
)
   , u as (
    select id, c.email
    from "user"
             cross join constants c
    where "user".email = c.email
    limit 1
)
   , a as (
    insert into assessment ("createdAt", "type", "rscId", "userId")
        select distinct
            c."createdAt"::timestamp,
            c.type,
            c."rscId",
            u.id
        from data
                 cross join constants c
                 join u on u.email = c.email
        returning id, "rscId"
)
   , q as (
    select id, data.name
    from question
             join data on question.name = data.name
    where question.name = data.name
)
insert into response ("selection", "assessmentId", "questionId")
select selection, a.id as "assessmentId", q.id as "questionId"
from data
         join a on a."rscId" = (select "rscId" from constants)
         join q on q.name = data.name
         cross join constants c
         join u on u.email = c.email;
