#!/bin/bash
# Auto-generated by Terraform (open_cti.tf, via templatefile()) as the first
# part of aws_instance.open_cti's user_data. Do NOT edit the deployed copy by
# hand -- it's only ever regenerated by a fresh `terraform apply` (and even
# then only takes effect on a genuine first boot; user_data_replace_on_change
# = false means editing this template alone never touches the running
# instance -- see open_cti.tf's comment on that resource for why).
#
# This is the one place per-environment, non-secret open-cti config lives --
# see infrastructure/vars.tf (open_cti_host and friends) for the source
# variables and infrastructure/*.tfvars for the actual per-environment
# values. open-cti/bootstrap.sh AND open-cti/refresh-repo.sh (both run every
# boot by open-cti-render-env.service) source the file this writes to pick
# these values back up; neither re-derives them itself.
set -euo pipefail

mkdir -p /opt/open-cti

cat > /opt/open-cti/env.deploy <<'ENV_DEPLOY_EOF'
OPEN_CTI_SSM_PATH_PREFIX="${ssm_path_prefix}"
OPEN_CTI_REPO_URL="${repo_url}"
OPEN_CTI_REPO_BRANCH="${repo_branch}"
OPENCTI_HOST="${opencti_host}"
OPENCTI_ADMIN_EMAIL="${opencti_admin_email}"
SMTP_HOSTNAME="${smtp_hostname}"
CENSYS_ORG_ID="${censys_org_id}"
QUALYS_API_USERNAME="${qualys_api_username}"
XTM_ONE_HOST="${xtm_one_host}"
XTM_ONE_ADMIN_EMAIL="${xtm_one_admin_email}"
ENV_DEPLOY_EOF
