"""
Django settings for xfd_django project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# Standard Python Libraries
import logging.config
import mimetypes
import os

# Python built-in
from pathlib import Path

# Third-Party Libraries
from django.contrib.messages import constants as messages

from .helpers.log_helpers import install_xfd_prefix

mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("text/html", ".html", True)

install_xfd_prefix()  # Install custom logger prefix

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_KEY")
CROSSFEED_SUPPORT_EMAIL_SENDER = os.getenv("CROSSFEED_SUPPORT_EMAIL_SENDER")
CROSSFEED_SUPPORT_EMAIL_REPLYTO = os.getenv("CROSSFEED_SUPPORT_EMAIL_REPLYTO")
FRONTEND_DOMAIN = os.getenv("FRONTEND_DOMAIN")
IS_LOCAL = os.getenv("IS_LOCAL")
NIST_API_KEY = os.getenv("NIST_API_KEY")

# JWT Secret Key
JWT_SECRET = os.getenv("JWT_SECRET")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")
JWT_TIMEOUT_HOURS = os.getenv("JWT_TIMEOUT_HOURS")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = IS_LOCAL != "false"

ALLOWED_HOSTS = [
    ".execute-api.us-east-1.amazonaws.com",
    os.getenv("BACKEND_DOMAIN"),
    os.getenv("VITE_API_URL"),
    os.getenv("FRONTEND_DOMAIN"),
    os.getenv("CROSSFEED_FRONTEND_DOMAIN"),
    os.getenv("CROSSFEED_BACKEND_DOMAIN"),
]

MESSAGE_TAGS = {
    messages.DEBUG: "alert-secondary",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}

# Application definition

INSTALLED_APPS = [
    "netfields",
    "django.contrib.contenttypes",
    "xfd_api.apps.XfdApiConfig",
    "xfd_mini_dl.apps.XfdMiniDlConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
]


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USERNAME"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": "5432",
        "TEST": {
            "NAME": "crossfeed_test",  # Name of the test database
        },
    },
    "mini_data_lake": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",  # Replace with your database engine
        "NAME": os.getenv("MDL_NAME"),
        "USER": os.getenv("MDL_USERNAME"),
        "PASSWORD": os.getenv("MDL_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": "5432",
        "TEST": {
            "NAME": "mini_data_lake_test",  # Name of the test database
        },
    },
    "mini_data_lake_secondary": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",  # Replace with your database engine
        "NAME": os.getenv("MDL_SECONDARY_NAME"),
        "USER": os.getenv("MDL_USERNAME"),
        "PASSWORD": os.getenv("MDL_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": "5432",
        "TEST": {
            "NAME": "mini_data_lake_secondary_test",  # Name of the test database
        },
    },
}

DATABASE_ROUTERS = ["xfd_django.db_routers.MyAppRouter"]

# ElastiCache AWS
ELASTICACHE_ENDPOINT = os.getenv("ELASTICACHE_ENDPOINT")

# Elasticsearch
ELASTICSEARCH_ENDPOINT = os.getenv("ELASTICSEARCH_ENDPOINT")

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# Log Level defaults to INFO, can be changed to DEBUG in development
LOGGING_LEVEL = "DEBUG" if DEBUG else "INFO"
ROOT_LEVEL = "INFO"
# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "standard": {
            "format": "[%(asctime)s.%(msecs)03d] %(levelname)s [%(name)s:%(funcName)s:line %(lineno)d] - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "level": LOGGING_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": ROOT_LEVEL,
    },
    "loggers": {
        "xfd": {
            "handlers": ["console"],
            "level": LOGGING_LEVEL,
            "propagate": False,
        },
    },
}
# Apply the logging configuration
logging.config.dictConfig(LOGGING)

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

PROJECT_NAME = "XFD Python API"

DJANGO_SETTINGS_MODULE = "xfd_django.settings"

# Ensure cookies are only sent over HTTPS
SESSION_COOKIE_SECURE = not IS_LOCAL  # Only secure in production
CSRF_COOKIE_SECURE = not IS_LOCAL

# Prevent JavaScript access to cookies to mitigate XSS attacks
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# SameSite policy to prevent CSRF via cross-origin requests
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

DMZ_API_HEADER = {
    "X-API-KEY": os.getenv("CF_API_KEY"),
    "access_token": os.getenv("PE_API_KEY"),
    "Content-Type": "",
}
# Awaiting implementation of Matomo CSP, uncomment when ready
MATOMO_CONTENT_SECURITY_POLICY = {
    "default-src": ["*", "'unsafe-inline'", "'unsafe-eval'"],
    "connect-src": ["*"],
    "img-src": ["*"],
    "style-src": ["*", "'unsafe-inline'"],
    "frame-ancestors": ["*"],
    "frame-src": ["*"],
}


# SECURITY CONFIGURATION
SECURE_HSTS_SECONDS = 31536000  # Enable HSTS for 1 year
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_CACHE_CONTROL = "no-cache, no-store, must-revalidate"
SECURE_CSP_POLICY = {
    "default-src": ["'self'"],
    "connect-src": [
        "'self'",
        os.getenv("COGNITO_URL"),
        os.getenv("BACKEND_DOMAIN"),
        os.getenv("CROSSFEED_BACKEND_DOMAIN"),
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui-bundle.js",
    ],
    "frame-src": ["'self'", "https://www.dhs.gov/ntas/"],
    "img-src": [
        "'self'",
        "data:",
        os.getenv("FRONTEND_DOMAIN"),
        os.getenv("CROSSFEED_FRONTEND_DOMAIN"),
        "https://www.ssa.gov",
        "https://www.dhs.gov",
        "https://fastapi.tiangolo.com/img/favicon.png",
    ],
    "object-src": ["'none'"],
    "script-src": [
        "'self'",
        os.getenv("BACKEND_DOMAIN"),
        os.getenv("CROSSFEED_BACKEND_DOMAIN"),
        "https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js",
        "https://www.ssa.gov/accessibility/andi/fandi.js",
        "https://www.ssa.gov/accessibility/andi/andi.js",
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui-bundle.js",
        "'sha256-QOOQu4W1oxGqd2nbXbxiA1Di6OHQOLQD+o+G9oWL8YY='",
        "https://www.dhs.gov",
    ],
    "style-src": [
        "'self'",
        "'unsafe-inline'",
        "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui.css",
    ],
    "frame-ancestors": ["'none'"],
}
SECURE_ACCESS_CONTROL_ALLOW_CREDENTIALS = True
