# yamllint disable

---
name: Regression Testing

on:
  push:
    branches:
      - develop
      - integration
    paths:
      - frontend/**
      - .github/workflows/regression.yml
  pull_request:
    branches:
      - develop
      - integration
    paths:
      - frontend/**
      - .github/workflows/frontend.yml

defaults:
  run:
    working-directory: ./playwright

jobs:
  test_staging:
    runs-on: ubuntu-latest
    environment: staging
    timeout-minutes: 60
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SUBNET: ${{ secrets.AWS_SUBNET }}
      AWS_SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP }}
      AUTOMATED_TEST_REPORTS_BUCKET_NAME: cisa-crossfeed-staging-cd-automated-test-reports
      PW_XFD_URL: http://xfd-frontend-1:3000/
      PW_XFD_USERNAME: ${{ secrets.PW_XFD_USERNAME }}
      PW_XFD_PASSWORD: ${{ secrets.PW_XFD_PASSWORD }}
      PW_XFD_2FA_SECRET: ${{ secrets.PW_XFD_2FA_SECRET }}
      PW_XFD_LOGIN: ${{ secrets.PW_XFD_USERNAME }}
      PW_HEADLESS: true
      ENVIRONMENT: staging
      GIT_BRANCH: develop
    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables for staging
        run: echo "ENVIRONMENT=staging" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: |
         chmod +x run_playwright_tests.sh
         CLUSTER_NAME=crossfeed-playwright-staging-cd-ecs-cluster \
         TASK_DEFINITION=crossfeed-staging-cd-playwright-worker \
         ./run_playwright_tests.sh

        continue-on-error: false  # Ensure it stops if the ECS task fails

      - name: Download test report from S3
        run: |
          mkdir -p ./playwright-report/html
          aws s3 cp \
            "s3://$AUTOMATED_TEST_REPORTS_BUCKET_NAME/staging/playwright-reports/latest/html/" \
            ./playwright-report/html/ --recursive

          aws s3 cp \
            "s3://$AUTOMATED_TEST_REPORTS_BUCKET_NAME/staging/playwright-reports/latest/results.json" \
            ./playwright-report/results.json


      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: ./playwright-report/html/

      - name: Upload Playwright results JSON
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results-json
          path: ./playwright-report/results.json


  test_integration:
     runs-on: ubuntu-latest
     environment: integration
     timeout-minutes: 60
     if: github.event_name == 'push' && github.ref == 'refs/heads/integration'
     env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SUBNET: ${{ secrets.AWS_SUBNET }}
      AWS_SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP }}
      AUTOMATED_TEST_REPORTS_BUCKET_NAME: cisa-crossfeed-integration-automated-test-reports
      PW_XFD_URL: http://xfd-frontend-1:3000/
      PW_XFD_USERNAME: ${{ secrets.PW_XFD_USERNAME }}
      PW_XFD_PASSWORD: ${{ secrets.PW_XFD_PASSWORD }}
      PW_XFD_2FA_SECRET: ${{ secrets.PW_XFD_2FA_SECRET }}
      PW_XFD_LOGIN: ${{ secrets.PW_XFD_USERNAME }} # or hardcode if needed
      PW_HEADLESS: true
      ENVIRONMENT: integration
      GIT_BRANCH: integration
     steps:
      - uses: actions/checkout@v3

      - name: Set environment variables for integration
        run: echo "ENVIRONMENT=integration" >> $GITHUB_ENV

      - name: Run Playwright tests
        working-directory: ./playwright
        run: |
          chmod +x run_playwright_tests.sh
          CLUSTER_NAME=crossfeed-playwright-integration-ecs-cluster \
          TASK_DEFINITION=crossfeed-integration-playwright-worker \
          ./run_playwright_tests.sh

        continue-on-error: false  # Ensure it stops if the ECS task fails

      - name: Download test report from S3
        run: |
          mkdir -p ./playwright-report/html
          aws s3 cp \
          "s3://${AUTOMATED_TEST_REPORTS_BUCKET_NAME}/integration/playwright-reports/html/" \
          ./playwright-report/html/ --recursive

          aws s3 cp \
            "s3://$AUTOMATED_TEST_REPORTS_BUCKET_NAME/integration/playwright-reports/latest/results.json" \
            ./playwright-report/results.json


      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: ./playwright-report/html/

      - name: Upload Playwright results JSON
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results-json
          path: ./playwright-report/results.json
